---
# Source: helm-webapp-cve-consumer/templates/db_secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: webapp-db-secrets
  namespace: cve-consumer-ns
type: Opaque 
data:
  flyway_password: YXNkZjEyMzQK
---
# Source: helm-webapp-cve-consumer/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: webapp-pull-secrets
  namespace: cve-consumer-ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ZWFzeSB0aGVyZSBoYWNrZXIK
---
# Source: helm-webapp-cve-consumer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
  namespace: cve-consumer-ns
data:
  host: webapp-postgresql.cve-consumer-ns.svc.cluster.local 
  db: cve
  flyway_url: jdbc:postgresql://webapp-postgresql.cve-consumer-ns.svc.cluster.local:5432/cve
  flyway_user: piyush
  flyway_schema: cve
---
# Source: helm-webapp-cve-consumer/templates/deployments.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: cve-consumer-ns
spec:
  selector:
    matchLabels:
      app: webapp 
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp 
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: db-migrate
        image: dongrep/webapp_db_migrate:latest
        imagePullPolicy: Always
        env:
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: webapp-configmap
              key: flyway_url
        - name: FLYWAY_USER
          valueFrom:
            configMapKeyRef:
              name: webapp-configmap
              key: flyway_user
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webapp-db-secrets
              key: flyway_password
        - name: FLYWAY_DEFAULT_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: webapp-configmap
              key: flyway_schema

      containers:
      - name: webapp-cve-consumer
        image: dongrep/webapp_cve_consumer:latest
        imagePullPolicy: Always
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: webapp-configmap
                key: host
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: webapp-configmap
                key: flyway_user
          - name: PWD
            valueFrom:
              secretKeyRef:
                name: webapp-db-secrets
                key: flyway_password
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: webapp-configmap
                key: db
              
      imagePullSecrets:
      - name: webapp-pull-secrets
