name: webapp
namespace: cve-consumer

replicas: 3
restartPolicy: OnFailure

container:
  name: webapp-cve-consumer
  image: dongrep/webapp_cve_consumer
  tag: latest
  imagePullPolicy: Always

initcontainer:
  name: db-migrate
  image: dongrep/webapp_db_migrate
  tag: latest
  imagePullPolicy: Always

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  dockerConfig: ZWFzeSB0aGVyZSBoYWNrZXIK

db_secrets:
  flyway:
    password: YXNkZjEyMzQK
  type: Opaque

configMap:
  host: webapp-postgresql.cve-consumer.svc.cluster.local
  db: cve
  brokers: webapp-kafka.kafka-cve.svc.cluster.local:9092
  topic: cve
  flyway:
    url: jdbc:postgresql://webapp-postgresql.cve-consumer.svc.cluster.local:5432/cve
    user: piyush
    schema: cve
