name: webapp
namespace: cve-consumer

replicas: 3
restartPolicy: Always

container:
  name: webapp-cve-consumer
  image: dongrep/webapp_cve_consumer
  tag: latest
  imagePullPolicy: Always

initcontainer:
  name: db-migrate
  image: dongrep/webapp_db_migrate
  tag: latest
  imagePullPolicy: Always

imagePullSecrets:
  type: kubernetes.io/dockerconfigjson
  dockerConfig: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkb25ncmVwIiwicGFzc3dvcmQiOiJkY2tyX3BhdF83THFJSjcxSWpZVXNyMTJkRXhZdk12dU9aeXMiLCJhdXRoIjoiWkc5dVozSmxjRHBrWTJ0eVgzQmhkRjgzVEhGSlNqY3hTV3BaVlhOeU1USmtSWGhaZGsxMmRVOWFlWE09In19fQ== 

db_secrets:
  openai_api_key: c2stcHJvai05X05rVnJjWV9KOC1ZMmh6RmZrM1E5b0pmYVFmcGdiZy1xLUkzbHdUUmd1alR4NVhjY0c1ZnZNMkpDVDNCbGJrRkpaMG5rbkhRU21tMW83NDFuUjhuVFhoSFI5MGlxZHNaNGFtSVUyWG9oV1pzTUgwalNyWlh5dERWbGtBCg==
  flyway:
    password: S1FlUDhYQVNCVktk
  type: Opaque

configMap:
  host: webapp-postgresql.cve-consumer.svc.cluster.local
  db_port: 5432
  db: cve
  brokers: webapp-kafka.kafka-ns.svc.cluster.local:9092
  topic: cve
  group_id: cve-consumer
  flyway:
    url: jdbc:postgresql://webapp-postgresql.cve-consumer.svc.cluster.local:5432/cve
    user: piyush
    schema: cve

resources:
  requests:
    cpu: "5m"
    memory: "50Mi"
  limits:
    cpu: "20m"
    memory: "200Mi"

autoscaling:
  minReplicas: "3"
  maxReplicas: "6"
  targetCPUUtilizationPercentage: "80"

pdb:
  minAvailable: "3"
  # maxUnavailable: "1"

rbac:
  automountServiceAccountToken: false
