
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-db-secrets
  namespace: {{ .Values.namespace }}
type: {{ .Values.db_secrets.type }} 
data:
  flyway_password: {{ .Values.db_secrets.flyway.password }}
  openai_api_key: {{ .Values.db_secrets.openai_api_key }}
